<a href="https://colab.research.google.com/github/Pkaur-101/INVENTORY_M/blob/master/assignment1_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
reversed_arr=arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [4]:
import numpy as np
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened_arr=array1.flatten()
print(flattened_arr)

[1 2 3 2 4 5 1 2 3]


In [5]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
comparison=arr1==arr2
equal_array=comparison.all()
print(equal_array)


True


In [6]:
import numpy as np
x=np.array([1,2,3,4,5,1,2,1,1,1])
print("original array")
print(x)
print("Most frequent value in the array")
print(np.bincount(x).argmax())

original array
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the array
1


In [7]:
import numpy as np
y=np.array([1,1,1,2,3,4,2,4,3,3])
print("ORIGINAL ARRAY")
print(y)
print("most frequent value in the array")
print(np.bincount(y).argmax())

ORIGINAL ARRAY
[1 1 1 2 3 4 2 4 3 3]
most frequent value in the array
1


In [8]:
import numpy as np
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
column_sum = gfg.sum(axis=0)
print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_sum)
print("Sum of all elements column-wise:", column_sum)


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [9]:
import numpy as np
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
sum_diagonal = np.trace(n_array)
eigenvalues = np.linalg.eigvals(n_array)
eigenvalues, eigenvectors = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print("Sum of diagonal elements:", sum_diagonal)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("Inverse of matrix:\n", inverse_matrix)
print("Determinant of matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [13]:
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product = np.dot(p, q)
print("Product of matrices p and q:\n", product)
p_flat = p.flatten()
q_flat = q.flatten()
covariance = np.cov(p_flat, q_flat)
print("\nCovariance of matrices p and q:\n", covariance)


Product of matrices p and q:
 [[16 19]
 [26 31]]

Covariance of matrices p and q:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


In [14]:
import numpy as np
p=np.array([[1,2],[2,3],[4,5]])
q=np.array([[4,5,1],[6,7,2]])
product=np.dot(p,q)
print("product of matrics p and q:\n",product)
p_flat=p.flatten()
q_flat=q.flatten()
covariance = np.cov(p_flat,q_flat)
print(covariance)

product of matrics p and q:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [15]:
import numpy as np
from itertools import product
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner product of x and y:\n", inner_product)
outer_product = np.outer(x.flatten(), y.flatten())
print("\nOuter product of x and y:\n", outer_product)
cartesian_product = np.array(list(product(x.flatten(), y.flatten())))
print("\nCartesian product of x and y:\n", cartesian_product)


Inner product of x and y:
 [[17 52]
 [13 62]]

Outer product of x and y:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product of x and y:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [16]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
absolute_value = np.abs(array)
print("Element-wise absolute value:\n", absolute_value)


Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
flattened_percentiles = np.percentile(array.flatten(), [25, 50, 75])
print("Percentiles of flattened array (25th, 50th, 75th):", flattened_percentiles)
column_percentiles = np.percentile(array, [25, 50, 75], axis=0)
print("\nPercentiles for each column (25th, 50th, 75th):\n", column_percentiles)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print("\nPercentiles for each row (25th, 50th, 75th):\n", row_percentiles)


Percentiles of flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]

Percentiles for each column (25th, 50th, 75th):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles for each row (25th, 50th, 75th):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [18]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])

flattened_mean = np.mean(array.flatten())
flattened_median = np.median(array.flatten())
flattened_std = np.std(array.flatten())

print("Flattened array:")
print("Mean:", flattened_mean)
print("Median:", flattened_median)
print("Standard Deviation:", flattened_std)

column_mean = np.mean(array, axis=0)
column_median = np.median(array, axis=0)
column_std = np.std(array, axis=0)

print("\nColumn-wise statistics:")
print("Mean:", column_mean)
print("Median:", column_median)
print("Standard Deviation:", column_std)

row_mean = np.mean(array, axis=1)
row_median = np.median(array, axis=1)
row_std = np.std(array, axis=1)

print("\nRow-wise statistics:")
print("Mean:", row_mean)
print("Median:", row_median)
print("Standard Deviation:", row_std)


Flattened array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Column-wise statistics:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Row-wise statistics:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


In [19]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)
print("Original array:", a)
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [20]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Original array:", array)
print("Sorted array:", sorted_array)


Original array: [ 10  52  62  16  16  54 453]
Sorted array: [ 10  16  16  52  54  62 453]


In [21]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_indices = np.argsort(array)
print("Original array:", array)
print("Indices of sorted array:", sorted_indices)


Original array: [ 10  52  62  16  16  54 453]
Indices of sorted array: [0 3 4 1 5 2 6]
